name: Update Credly Badges

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily
  workflow_dispatch:      # Allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: shauraj-kumar
          BADGE_SIZE: 110

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update credly badges"
